FROM php:8.0-cli
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
RUN apt update && apt install git zip unzip -y
WORKDIR /app
COPY composer.json .
COPY composer.lock .
ENTRYPOINT ["composer"]
